@extends('frontend.master')

@php($pageTitle ='PBS Universal Accountholder Agreement')

@section('meta')
    <meta name="description" content="Review the PBS Universal Accountholder Agreement terms and conditions for property management and monitoring services in NYC.">
@stop

@section('css')
    {{--css kodları--}}

@stop

@section('slider')
    {{--slider bölümü--}}

@stop


@section('content')
    {{--content bölümü--}}
    <!-- Content
    ============================================= -->

    <section class="bg-transparent" id="content">

        <div class="content-wrap">

            <div class="section karbonopak">
                <div class="container clearfix">
                    <div class="row">
                        <div class="col-lg-12 center text-justify">
                            <blockquote class="quote p-1 nomargin">
                                <br/><br/>
                                <h1>PBS Accountholder Billing Agreement</h1>

                            </blockquote>
                            <blockquote class="quote blockquote-reverse nobottommargin">

                            </blockquote>
                            <br/>
                            <br/>
                            <span class="text-justify">
                                     <p>

Proactive Building Solutions
Billing Agreement

THIS BILLING AGREEMENT GOVERNS CUSTOMER’S ACQUISITION AND USE OF PROACTIVE BUILDING SOLUTIONS (PBS) SERVICES. CAPITALIZED TERMS HAVE THE DEFINITIONS SET FORTH HEREIN.
BY ACCEPTING THIS AGREEMENT, BY (1) READING THE AGREEMENT PAGE (www.pbs.nyc/billing-aggreement) INDICATING ACCEPTANCE, (2) EXECUTING A SUBSCRIPTION THAT REFERENCES THIS AGREEMENT CUSTOMER AGREES TO THE TERMS OF THIS AGREEMENT. IF THE INDIVIDUAL ACCEPTING THIS AGREEMENT IS ACCEPTING ON BEHALF OF A COMPANY OR OTHER LEGAL ENTITY, SUCH INDIVIDUAL REPRESENTS THAT THEY HAVE THE AUTHORITY TO BIND SUCH ENTITY AND ITS AFFILIATES TO THESE TERMS AND CONDITIONS, IN WHICH CASE THE TERM “CUSTOMER” SHALL REFER TO SUCH ENTITY AND ITS AFFILIATES. IF THE INDIVIDUAL ACCEPTING THIS AGREEMENT DOES NOT HAVE SUCH AUTHORITY, OR DOES NOT AGREE WITH THESE TERMS AND CONDITIONS, SUCH INDIVIDUAL MUST NOT ACCEPT THIS AGREEMENT AND MAY NOT USE THE SERVICES.
The Services may not be accessed for purposes of monitoring their availability, performance or functionality, or for any other benchmarking or competitive purposes.
PBS’s direct competitors are prohibited from accessing the Services, except with PBS’s prior written consent.
This Agreement was last updated on July 2020. It is effective between Customer and PBS as of the date of Customer’s accepting this Agreement.
</p><h1>1.	DEFINITIONS</h1><p>
“Affiliate” means any entity that directly or indirectly controls, is controlled by, or is under common control with the subject entity. “Control,” for purposes of this definition, means direct or indirect ownership or control of more than 50% of the voting interests of the subject entity.
“Agreement” means this Billing Agreement.
 “Content” means information obtained by PBS from publicly available sources or its third party content providers and made available to Customer through the Services and/or Beta Services, as more fully described in the Documentation.
“Customer” means in the case of an individual accepting this Agreement on his or her own behalf, such individual, or in the case of an individual accepting this Agreement on behalf of a company or other legal entity, the company or other legal entity for which such individual is accepting this Agreement, and Affiliates of that company or entity (for so long as they remain Affiliates) which have a billing process.
“Customer Data” means electronic data and information submitted by or for Customer to the Services, excluding Content and Non-PBS Applications.

“Free Services” means Services that PBS makes available to Customer free of charge. Free Services exclude Services offered as Purchased Services. All of the public services are free of charge on www.pbs.nyc .
 “Non-PBS Application” means a Web-based, mobile, offline or other software application functionality that interoperates with a Service, that is provided by Customer or a third party. Non-PBS Applications, other than those obtained or provided by Customer, will be identifiable as such.
“Subscription Form” means an ordering document or online order specifying the Services to be provided hereunder that is entered into between Customer and PBS or any of their Affiliates, including any addenda and supplements thereto. By entering into an Subscription Form hereunder, an Affiliate agrees to be bound by the terms of this Agreement as if it were an original party hereto.
“Purchased Services” means Services that Customer or Customer’s Affiliate purchases under an Subscription Form or online purchasing portal.
“Services” means the products and services that are ordered by Customer under an Subscription Form or online purchasing portal, or provided to Customer free of charge (as applicable), and made available online by PBS, including associated  offline or mobile components, as described in the Documentation. “Services” exclude Content and Non-PBS Applications.
“PBS” means the “PROACTIVE BUILDING SOLUTIONS” company described in the “PBS Contracting Entity, Notices, Governing Law, and Venue” section below.
“User” or “Client” means, in the case of an individual accepting these terms on his or her own behalf, such individual, or, in the case of an individual accepting this Agreement on behalf of a company or other legal entity, an individual who is authorized by Customer to use a Service, for whom Customer has purchased a subscription (or in the case of any Services provided by PBS without charge, for whom a Service has been provisioned), and to whom Customer (or, when applicable, PBS at Customer’s request) has supplied a user identification and password (for Services utilizing authentication). Users may include, for example, employees, consultants, contractors and agents of Customer, and third parties with which Customer transacts business.
</p><h1>2.	PBS RESPONSIBILITIES</h1><p>

<br/>2.1	Provision of Purchased Services. PBS will (a) make the Services and Content available to Customer pursuant to this Agreement, and the applicable Subscription Forms, (b) provide applicable PBS standard support for the Purchased Services to Customer at no additional charge, and/or upgraded support if purchased, (c) use commercially reasonable efforts to make the online Purchased Services available 24 hours a day, 7 days a week, except for: (i) planned downtime (of which PBS shall give advance electronic notice), and (ii) any unavailability caused by circumstances beyond PBS’s reasonable control, including, for example, an act of God, act of government, flood, fire, earthquake, civil unrest, act of terror, strike or other labor problem (other than one involving PBS employees), Internet service provider failure or delay, Non-PBS Application, or denial of service attack, and (d) provide the Services in accordance with laws and government regulations applicable to PBS’s provision of its Services to its customers generally (i.e., without regard for Customer’s particular use of the Services), and subject to Customer’s use of the Services.
<br/><br/>2.2	Protection of Customer Data. PBS will maintain appropriate administrative, physical, and technical safeguards for protection of the security, confidentiality and integrity of Customer Data. Those safeguards will include, but will not be limited to, measures designed to prevent unauthorized access to or disclosure of Customer Data (other than by Customer or Users).
<br/><br/>2.3	PBS Personnel. PBS will be responsible for the performance of its personnel (including its employees and contractors) and their compliance with PBS’s obligations under this Agreement, except as otherwise specified in this Agreement.
ANY DATA CUSTOMER ENTERS INTO THE SERVICES, AND ANY CUSTOMIZATIONS MADE TO THE SERVICES BY OR FOR CUSTOMER, PURCHASES APPLICABLE UPGRADED SERVICES, OR EXPORTS SUCH DATA.
NOTWITHSTANDING THE “REPRESENTATIONS, WARRANTIES, EXCLUSIVE REMEDIES AND DISCLAIMERS” SECTION AND “INDEMNIFICATION BY PBS” SECTION BELOW, FOR THE FREE PARTS OF THE PBS THE SERVICES ARE PROVIDED “AS-IS” WITHOUT ANY WARRANTY AND PBS SHALL HAVE NO INDEMNIFICATION OBLIGATIONS NOR LIABILITY OF ANY TYPE WITH RESPECT TO THE SERVICES FOR THE FREE PERIOD UNLESS SUCH EXCLUSION OF LIABILITY IS NOT ENFORCEABLE UNDER APPLICABLE LAW IN WHICH CASE PBS’S LIABILITY WITH RESPECT TO THE SERVICES PROVIDED DURING THE FREE PERIOD SHALL NOT EXCEED $1,000.00. WITHOUT LIMITING THE FOREGOING, PBS AND ITS AFFILIATES AND ITS LICENSORS DO NOT REPRESENT OR WARRANT TO CUSTOMER THAT: (A) CUSTOMER’S USE OF THE SERVICES DURING THE FREE PERIOD WILL MEET CUSTOMER’S REQUIREMENTS, (B) CUSTOMER’S USE OF THE SERVICES DURING THE FREE PERIOD WILL BE UNINTERRUPTED, TIMELY, SECURE OR FREE FROM ERROR, AND
(C) USAGE DATA PROVIDED DURING THE FREE PERIOD WILL BE ACCURATE. NOTWITHSTANDING ANYTHING TO THE CONTRARY IN THE “LIMITATION OF LIABILITY” SECTION BELOW, CUSTOMER SHALL BE FULLY LIABLE UNDER THIS AGREEMENT TO PBS AND ITS AFFILIATES FOR ANY DAMAGES ARISING OUT OF CUSTOMER’S USE OF THE SERVICES DURING THE FREE TRIAL PERIOD, ANY BREACH BY CUSTOMER OF THIS AGREEMENT AND ANY OF CUSTOMER’S INDEMNIFICATION OBLIGATIONS HEREUNDER.
CUSTOMER SHALL REVIEW THE APPLICABLE SERVICE’S DOCUMENTATION DURING THE TRIAL PERIOD TO BECOME FAMILIAR WITH THE FEATURES AND FUNCTIONS OF THE SERVICES BEFORE MAKING A PURCHASE.
<br/><br/>2.4	Free Services. PBS may make Free Services available to Customer. Use of Free Services is subject to the terms and conditions of this Agreement. In the event of a conflict between this section and any other portion of this Agreement, this section shall control. Free Services are provided to Customer without charge up to certain limits as described in the Documentation. Usage over these limits requires Customer’s purchase of additional resources or services.  Customer agrees that PBS, in its sole discretion and for any or no reason, may terminate Customer’s access to the Free Services or any part thereof. Customer agrees that any termination of Customer’s access to the Free Services may be without prior notice, and Customer agrees that PBS will not be liable to Customer or any third party for such termination. Customer is solely responsible for exporting Customer Data from the Free Services prior to termination of Customer’s access to the Free Services for any reason, provided that if PBS terminates Customer’s account, except as required by law PBS will provide Customer a reasonable opportunity to retrieve its Customer Data.
NOTWITHSTANDING THE “REPRESENTATIONS, WARRANTIES, EXCLUSIVE REMEDIES AND DISCLAIMERS” SECTION AND “INDEMNIFICATION BY PBS” SECTION BELOW, THE FREE SERVICES ARE PROVIDED “AS-IS” WITHOUT ANY WARRANTY AND PBS SHALL HAVE NO INDEMNIFICATION OBLIGATIONS NOR LIABILITY OF ANY TYPE WITH RESPECT TO THE FREE SERVICES UNLESS SUCH EXCLUSION OF LIABILITY IS NOT ENFORCEABLE UNDER APPLICABLE LAW IN WHICH CASE PBS’S LIABILITY WITH RESPECT TO THE FREE SERVICES SHALL NOT EXCEED $1,000.00. WITHOUT LIMITING THE FOREGOING, PBS AND ITS AFFILIATES AND ITS LICENSORS DO NOT REPRESENT OR WARRANT TO CUSTOMER THAT: (A) CUSTOMER’S USE OF THE FREE SERVICES WILL MEET CUSTOMER’S REQUIREMENTS, (B) CUSTOMER’S USE OF THE FREE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE OR FREE FROM ERROR, AND (C) USAGE DATA PROVIDED THROUGH THE FREE SERVICES WILL BE ACCURATE. NOTWITHSTANDING ANYTHING TO THE CONTRARY IN THE “LIMITATION OF LIABILITY” SECTION BELOW, CUSTOMER SHALL BE FULLY LIABLE UNDER THIS AGREEMENT TO PBS AND ITS AFFILIATES FOR ANY DAMAGES ARISING OUT OF CUSTOMER’S USE OF THE FREE SERVICES, ANY BREACH BY CUSTOMER OF THIS AGREEMENT AND ANY OF CUSTOMER’S INDEMNIFICATION OBLIGATIONS HEREUNDER.
</p><h1>3.	USE OF SERVICES AND CONTENT</h1><p>
<br/>3.1	Subscriptions. Unless otherwise provided in the applicable Subscribe Form, (a) Purchased Services and access to Content are purchased as subscriptions for the term stated in the applicable Subscribe Form or in the applicable online purchasing portal, (b) subscriptions for Purchased Services may be added during a subscription term at the same pricing as the underlying subscription pricing, prorated for the portion of that subscription term remaining at the time the subscriptions are added, and (c) any added subscriptions will terminate on the same date as the underlying subscriptions. Customer agrees that its purchases are not contingent on the delivery of any future functionality or features, or dependent on any oral or written public comments made by PBS regarding future functionality or features.
<br/><br/>3.2	Usage Limits. Services and Content are subject to usage limits specified in Subscribe Forms. If Customer exceeds a contractual usage limit, PBS may work with Customer to seek to reduce Customer’s usage so that it conforms to that limit. If, notwithstanding PBS’s efforts, Customer is unable or unwilling to abide by a contractual usage limit, Customer will execute an Subscribe Form for additional quantities of the applicable Services or Content promptly upon PBS’s request, and/or pay any invoice for excess usage in accordance with the “Invoicing and Payment” section below.
<br/><br/>3.3	Customer Responsibilities. Customer will (a) be responsible for Users’ compliance with this Agreement, Documentation and Order Forms, (b) be responsible for the accuracy, quality and legality of Customer Data, the means by which Customer acquired Customer Data, Customer’s use of Customer Data with the Services, and the interoperation of any Non-PBS Applications with which Customer uses Services or Content, (c) use commercially reasonable efforts to prevent unauthorized access to or use of Services and Content, and notify PBS promptly of any such unauthorized access or use, (d) use Services and Content only in accordance with this Agreement, the Acceptable Use, Subscribe Forms and applicable laws and government regulations, and (e) comply with terms of service of any Non-PBS Applications with which Customer uses Services or Content. Any use of the Services in breach of the foregoing by Customer or Users that in PBS’s judgment threatens the security, integrity or availability of PBS’s services, may result in PBS’s immediate suspension of the Services, however PBS will use commercially reasonable efforts under the circumstances to provide Customer with notice and an opportunity to remedy such violation or threat prior to any such suspension.
<br/><br/>3.4	Usage Restrictions. Customer will not (a) make any Service or Content available to anyone other than Customer or Users, or use any Service or Content for the benefit of anyone other than Customer or its Affiliates, unless expressly stated otherwise in an Subscribe Form, (b) sell, resell, license, sublicense, distribute, make available, rent or lease any Service or Content, or include any Service or Content in a service bureau or outsourcing offering, (c) use a Service or Non-PBS Application to store or transmit infringing, libelous, or otherwise unlawful or tortious material, or to store or transmit material in violation of third-party privacy rights, (d) use a Service or Non-PBS Application to store or transmit Malicious Code, (e) interfere with or disrupt the integrity or performance of any Service or third-party data contained therein, (f) attempt to gain unauthorized access to any Service or Content or its related systems or networks, (g) permit direct or indirect access to or use of any Services or Content in a way that circumvents a contractual usage limit, or use any Services to access or use any of PBS intellectual property except as permitted under this Agreement, an Order Form, or the Documentation, (h) modify, copy, or create derivative works based on a Service or any part, feature, function or user interface thereof, (i) copy Content except as permitted herein or in an Order Form or the Documentation, (j) frame or mirror any part of any Service or Content, other than framing on Customer's own intranets or otherwise for its own internal business purposes or as permitted in the Documentation,
(k) except to the extent permitted by applicable law, disassemble, reverse engineer, or decompile a Service or Content or access it to (1) build a competitive product or service, (2) build a product or service using similar ideas, features, functions or graphics of the Service, (3) copy any ideas, features, functions or graphics of the Service, or (4) determine whether the Services are within the scope of any patent.
<br/><br/>3.5	Removal of Content and Non-PBS Applications. If Customer receives notice that Content or a Non-PBS Application must be removed, modified and/or disabled to avoid violating applicable law, third-party rights, or the Acceptable Use and External Facing Services Policy, Customer will promptly do so. If Customer does not take required action in accordance with the above, or if in PBS’s judgment continued violation is likely to reoccur, PBS may disable the applicable Content, Service and/or Non-PBS Application. If requested by PBS, Customer shall confirm such deletion and discontinuance of use in writing and PBS shall be authorized to provide a copy of such confirmation to any such third-party claimant or governmental authority, as applicable. In addition, if PBS is required by any third-party rights holder to remove Content, or receives information that Content provided to Customer may violate applicable law or third-party rights, PBS may discontinue Customer’s access to Content through the Services.
</p><h1>4.	NON-PBS PRODUCTS AND SERVICES</h1><p>
<br/>4.1	Non-PBS Products and Services. PBS or third parties may make available (for example, through a Marketplace or otherwise) third-party products or services, including, for example, Non-PBS Applications and implementation and other consulting services. Any acquisition by Customer of such products or services, and any exchange of data between Customer and any Non-PBS provider, product or service is solely between Customer and the applicable Non-PBS provider. PBS does not warrant or support Non-PBS Applications or other Non-PBS products or services, whether or not they are designated by PBS as “certified” or otherwise, unless expressly provided otherwise in an Order Form. PBS is not responsible for any disclosure, modification or deletion of Customer Data resulting from access by such Non-PBS Application or its provider.
<br/><br/>4.2	Integration with Non-PBS Applications. The Services may contain features designed to interoperate with Non-PBS Applications. PBS cannot guarantee the continued availability of such Service features, and may cease providing them without entitling Customer to any refund, credit, or other compensation, if for example and without limitation, the provider of a Non-PBS Application ceases to make the Non-PBS Application available for interoperation with the corresponding Service features in a manner acceptable to PBS.
</p><h1>5.	FEES AND PAYMENT</h1><p>
<br/>5.1	Fees. Customer will pay all fees specified in Order Forms. Except as otherwise specified herein or in an Order Form, (i) fees are based on Services and Content subscriptions purchased and not actual usage, (ii) payment obligations are non- cancelable and fees paid are non-refundable, and (iii) quantities purchased cannot be decreased during the relevant subscription term.
<br/><br/>5.2	Invoicing and Payment. Customer will provide PBS with valid and updated credit card information. If Customer provides credit card information to PBS, Customer authorizes PBS to charge such credit card for all Purchased Services listed in the Subscribe Form for the initial subscription term and any renewal subscription term(s) as set forth in the “Term of Purchased Subscriptions” section below. Such charges shall be made in advance, either annually or in accordance with any different billing frequency stated in the applicable Subscribe Form. Unless otherwise stated in the Subscribe Form, invoiced fees are due net 30 days from the invoice date. Customer is responsible for providing complete and accurate billing and contact information to PBS and notifying PBS of any changes to such information.
</p><h1>6.	PROPRIETARY RIGHTS AND LICENSES</h1><p>
<br/>6.1	Reservation of Rights. Subject to the limited rights expressly granted hereunder, PBS, its Affiliates, its licensors and Content Providers reserve all of their right, title and interest in and to the Services and Content, including all of their related intellectual property rights. No rights are granted to Customer hereunder other than as expressly set forth herein.
</p><h1>7.	REPRESENTATIONS, WARRANTIES, EXCLUSIVE REMEDIES AND DISCLAIMERS</h1><p>
<br/>7.1	Representations. Each party represents that it has validly entered into this Agreement and has the legal power to do so.
<br/><br/>7.2	PBS Warranties. PBS warrants that during an applicable subscription term (a) this Agreement, the Order Forms and the Documentation will accurately describe the applicable administrative, physical, and technical safeguards for protection of the security, confidentiality and integrity of Customer Data, (b) PBS will not materially decrease the overall security of the Services, (c) the Services will perform materially in accordance with the applicable Documentation, and (d) subject to the “Integration with Non-PBS Applications” section above, PBS will not materially decrease the overall functionality of the Services. For any breach of a warranty above, Customer’s exclusive remedies are those described in the “Termination” section below.
<br/><br/>7.3	Disclaimers. EXCEPT AS EXPRESSLY PROVIDED HEREIN, NEITHER PARTY MAKES ANY WARRANTY OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, AND EACH PARTY SPECIFICALLY DISCLAIMS ALL IMPLIED WARRANTIES, INCLUDING ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW. CONTENT AND BETA SERVICES ARE PROVIDED “AS IS,” AND AS AVAILABLE EXCLUSIVE OF ANY WARRANTY WHATSOEVER.
</p><h1>8.	TERM AND TERMINATION</h1><p>
<br/>8.1	Term of Agreement. This Agreement commences on the date Customer first accepts it and continues until all subscriptions hereunder have expired or have been terminated.
<br/><br/>8.2	Term of Purchased Subscriptions. The term of each subscription shall be as specified in the applicable Subscribe Form.  Except as otherwise specified in an Subscribe Form, subscriptions will automatically renew for additional periods equal to the expiring subscription term or one year (whichever is shorter), unless either party gives the other written notice (email acceptable) at least 30 days before the end of the relevant subscription term. Except as expressly provided in the applicable Order Form, renewal  of promotional or one-time priced subscriptions will be at PBS’s applicable list price in effect at the time of the applicable renewal. Notwithstanding anything to the contrary, any renewal in which subscription volume or subscription length for any Services has decreased from the prior term will result in re-pricing at renewal without regard to the prior term’s per-unit pricing.
<br/><br/>8.3	Termination. A party may terminate this Agreement for cause (i) upon 30 days written notice to the other party of a material breach if such breach remains uncured at the expiration of such period, or (ii) if the other party becomes the subject of a petition in bankruptcy or any other proceeding relating to insolvency, receivership, liquidation or assignment for the benefit of creditors.
<br/><br/>8.4	Refund or Payment upon Termination. If this Agreement is terminated by Customer in accordance with the “Termination” section above, PBS will refund Customer any prepaid fees covering the remainder of the term of all Order Forms after the effective date of termination. If this Agreement is terminated by PBS in accordance with the “Termination” section above, Customer will pay any unpaid fees covering the remainder of the term of all Order Forms to the extent permitted by applicable law. In no event will termination relieve Customer of its obligation to pay any fees payable to PBS for the period prior to the effective date of termination.
<br/><br/>8.5	Surviving Provisions. The sections titled “Free Services,” “Fees and Payment,” “Proprietary Rights and Licenses,” “Confidentiality,” “Disclaimers,” “Mutual Indemnification,” “Limitation of Liability,” “Refund or Payment upon Termination,” “Removal of Content and Non-PBS Applications,” “Surviving Provisions” and “General Provisions” will survive any termination or expiration of this Agreement, and the section titled “Protection of Customer Data” will survive any termination or expiration of this Agreement for so long as PBS retains possession of Customer Data.
</p><h1>9.	GENERAL PROVISIONS</h1><p>
<br/>9.1	Entire Agreement and Order of Precedence. This Agreement is the entire agreement between PBS and  Customer regarding Customer’s use of Services and Content and supersedes all prior and contemporaneous agreements, proposals or representations, written or oral, concerning its subject matter. The parties agree that any term or condition stated in a Customer purchase order or in any other Customer order documentation (excluding Order Forms) is void. In the event of any conflict or inconsistency among the following documents, the order of precedence shall be: (1) the applicable Order Form, (2) this Agreement, and (3) the Documentation. Titles and headings of sections of this Agreement are for convenience only and shall not affect the construction of any provision of this Agreement.
<br/><br/>9.2	Relationship of the Parties. The parties are independent contractors. This Agreement does not create a partnership, franchise, joint venture, agency, fiduciary or employment relationship between the parties.
<br/><br/>9.3	Third-Party Beneficiaries. There are no third-party beneficiaries under this Agreement.
<br/><br/>9.4	Waiver. No failure or delay by either party in exercising any right under this Agreement will constitute a waiver of that right.
<br/><br/>9.5	Severability. If any provision of this Agreement is held by a court of competent jurisdiction to be contrary to law, the provision will be deemed null and void, and the remaining provisions of this Agreement will remain in effect.
<br/><br/>9.6	Assignment. Neither party may assign any of its rights or obligations hereunder, whether by operation of law or otherwise, without the other party’s prior written consent (not to be unreasonably withheld); provided, however, either party may assign this Agreement in its entirety (including all Order Forms), without the other party’s consent to its Affiliate or in connection with a merger, acquisition, corporate reorganization, or sale of all or substantially all of its assets.  Notwithstanding the foregoing, if a party is acquired by, sells substantially all of its assets to, or undergoes a change of control in favor of, a direct competitor of the other party, then such other party may terminate this Agreement upon written notice. In the event of such a termination, PBS will refund Customer any prepaid fees covering the remainder of the term of all subscriptions for the period after the effective date of such termination. Subject to the foregoing, this Agreement will bind and inure to the benefit of the parties, their respective successors and permitted assigns.
<br/><br/>9.7	PBS Contracting Entity, Notices, Governing Law, and Venue. The PBS entity entering into this Agreement, the address to which Customer should direct notices under this Agreement, the law that will apply in any dispute or lawsuit arising out of or in connection with this Agreement, and the courts that have jurisdiction over any such dispute or lawsuit, depend on where Customer is domiciled.
<br/><br/>9.8	Agreement to Governing Law and Jurisdiction. Each party agrees to the applicable governing law above without regard to choice or conflicts of law rules, and to the exclusive jurisdiction of the applicable courts above.
.
                                </p>
                                </span>

                        </div>

                    </div>
                </div>
            </div>


        </div>

    </section><!-- #content end -->
@stop


@section('js')
    {{--javascript bölümü--}}
@stop
