<?php

namespace App\Models;


use App\Helpers\Helper;

class DobCertOccupancy extends ODataModel
{
    public $subject = "New Certificates of Occupancy Filed";
    public $updateSubject = "New Certificates of Occupancy Status Update";
    public $mailview = 'mails.alerts.dobCertOccupancy';
    protected $datasetId = "bs8b-p36w";
    protected $datasetName = "DOB Certificates Of Occupancy";

    protected $dataColumn = "bin";
    protected $dataSocrataKey = "bin_number";

    protected $primaryKey = 'job_item_number';

    protected $table = 'dob_cert_occupancy';

    protected $updateFrequency = 'daily';

    protected $notifiables = [
        'c_o_issue_date',
        'application_status_raw',
    ];

    protected $selectables = [
        'job_number',
        'job_type',
        'c_o_issue_date',
        'bin_number',
        'application_status_raw',
        'item_number',
    ];

    protected $fillable = [
        'job_item_number',
        'job_number',
        'job_type',
        'c_o_issue_date',
        'bin_number',
        'borough',
        'house_number',
        'street_name',
        'block',
        'lot',
        'postcode',
        'pr_dwelling_unit',
        'ex_dwelling_unit',
        'application_status_raw',
        'filing_status_raw',
        'item_number',
        'issue_type',
        'latitude',
        'longitude',
        'community_board',
        'council_district',
        'census_tract',
        'bin',
        'bbl',
        'nta',
        'location'];

    protected $casts = [
        'location' => 'array',
        'job_number' => 'string',
        'item_number' => 'string',
    ];

    public function issuedDate()
    {
        return Helper::carbonParseYmd($this->c_o_issue_date);
    }

    public function insertData($result)
    {
        $result["job_item_number"] = $result["job_number"] . "_" . $result["item_number"];
        parent::insertData($result); // TODO: Change the autogenerated stub
    }

    public function scopeSummary($query)
    {
        return $query->where('c_o_issue_date', '>', now()->addMonths(-3)->format('Y-m-d') . 'T00:00:00.000');
    }

//    protected function getWhereString()
//    {
//        return parent::getWhereString() . " and
//        (
//           (c_o_issue_date > '" . now()->addMonths(-3)->format('Y-m-d') . "T00:00:00.000')
//        )";
//    }

    public function getBinAttribute()
    {
        return $this->bin_number;
    }

}
