<?php

namespace App\Models;


use App\Helpers\Helper;
use Carbon\Carbon;

class DobNowFacadeFilings extends ODataModel
{
    public $subject = "New DOB Now Facade Compliance Filed";
    public $updateSubject = "New DOB Now Facade Compliance Status Update";
    public $reminderSubject = "DOB Now Facade Compliance Reminder";
    public $mailview = 'mails.alerts.dobNowFacadeFilings';
    protected $datasetId = "xubg-57si";
    protected $datasetName = "DOB NOW: Safety – Facades Compliance Filings";

    protected $dataColumn = "bin";
    protected $dataSocrataKey = "bin";

    protected $primaryKey = 'tr6_no';

    protected $table = 'dob_now_facade_filings';

    protected $updateFrequency = 'daily';

    protected $notifiables = [
        'current_status',
        'filing_date',
    ];

    protected $selectables = [
        'tr6_no',
        'control_no',
        'filing_type',
        'cycle',
        'bin',
        'submitted_on',
        'current_status',
        'qewi_name',
        'filing_date',
    ];


    protected $fillable = [
        'tr6_no',
        'control_no',
        'filing_type',
        'cycle',
        'bin',
        'house_no',
        'street_name',
        'borough',
        'block',
        'lot',
        'sequence_no',
        'submitted_on',
        'current_status',
        'qewi_name',
        'qewi_bus_name',
        'qewi_bus_street_name',
        'qewi_city',
        'qewi_state',
        'qewi_zip',
        'qewi_nys_lic_no',
        'owner_name',
        'owner_bus_name',
        'owner_bus_street_name',
        'owner_city',
        'owner_zip',
        'owner_state',
        'filing_date',
        'filing_status',
        'prior_cycle_filing_date',
        'prior_status',
        'field_inspection_completed_date',
        'qewi_signed_date',
        'late_filing_amt',
        'failure_to_file_amt',
        'failure_to_collect_amt',
        'comments'];


    protected $casts = [
        'tr6_no' => 'string',
    ];

    public function submittedOn()
    {
        return Helper::carbonParseYmd($this->submitted_on);
    }


    public function scopeSummary($query)
    {
        return $query->where('current_status', '!=', 'SAFE')->orWhere(function ($query) {
            $query->where('current_status', '=', 'SAFE')
                ->where('filing_date', '>', now()->addYears(-1)->format('Y-m-d') . "T00:00:00.000");
        });
    }

//    protected function getWhereString()
//    {
//        return parent::getWhereString() . " and (
//        current_status != 'SAFE'
//        or (
//        current_status = 'SAFE'
//        and filing_date > '" . now()->addYears(-1)->format('Y-m-d') . "T00:00:00.000'
//        )
//       )"; // TODO: Change the autogenerated stub
//    }

}
