<?php
namespace App\Models;


use App\Helpers\Helper;

class DobNowApprovedPermits extends ODataModel
{
    public $subject = "New DOB Now Permit Issued";
    public $updateSubject = "New DOB Now Permit Status Update";
    public $mailview = 'mails.alerts.dobNowApprovedPermits';
    protected $datasetId = "rbx6-tga4";
    protected $datasetName = "DOB NOW: Build – Approved Permits";

    protected $dataColumn = "bin";
    protected $dataSocrataKey = "bin";

    protected $primaryKey = 'work_permit_issued_expired_date';

    protected $table = 'dob_now_approved_permits';

    protected $updateFrequency = 'daily';

    protected $notifiables = [
        'issued_date',
        'expired_date',
    ];

    protected $selectables = ['job_filing_number',
        'bin',
        'work_on_floor',
        'work_type',
        'permittee_s_license_type',
        'applicant_license',
        'work_permit',
        'issued_date',
        'expired_date',
    ];


    protected $fillable = [
        'work_permit_issued_expired_date',
        'job_filing_number',
        'filing_reason',
        'house_no',
        'street_name',
        'borough',
        'lot',
        'bin',
        'block',
        'c_b_no',
        'apt_condo_no_s',
        'work_on_floor',
        'work_type',
        'permittee_s_license_type',
        'applicant_license',
        'applicant_first_name',
        'applicant_middle_name',
        'applicant_last_name',
        'applicant_business_name',
        'applicant_business_address',
        'filing_representative_first_name',
        'filing_representative_middle_initial',
        'filing_representative_last_name',
        'filing_representative_business_name',
        'work_permit',
        'approved_date',
        'issued_date',
        'expired_date',
        'job_description',
        'estimated_job_costs',
        'owner_business_name',
        'owner_name',
        'owner_street_address',
        'owner_city',
        'owner_state',
        'owner_zip_code'];


    protected $casts = [
        'work_permit' => 'string',
        'issued_date' => 'string',
        'expired_date' => 'string',
    ];

    public function issuedDate()
    {
        return Helper::carbonParseYmd($this->issued_date);
    }

    public function insertData($result)
    {
        $result["work_permit_issued_expired_date"] = $result["work_permit"] . "_" . $result["issued_date"] . "_" . $result["expired_date"]. "_" . $result["work_type"];
        parent::insertData($result); // TODO: Change the autogenerated stub
    }

    public function scopeSummary($query)
    {
        return $query->where('issued_date','>',now()->addYears(-3)->format('Y') . "-01-01T00:00:00.000");
    }

//    protected function getWhereString()
//    {
//        return parent::getWhereString() . " and issued_date > '" . now()->addYears(-3)->format('Y') . "-01-01T00:00:00.000'"; // TODO: Change the autogenerated stub
//    }

}
