<?php

namespace App\Models;


use App\Helpers\Helper;

class FdnyCertOfFitness extends ODataModel
{
    public $subject = "New FDNY Certificates of Fitness Issued";
    public $updateSubject = "New FDNY Certificates of Fitness Status Update";
    public $reminderSubject = "FDNY Certificates of Fitness Status Reminder";
    public $mailview = 'mails.alerts.fdnyCertOfFitness';
    protected $datasetId = "pdiy-9ae5";
    protected $datasetName = "FDNY - Certificates of Fitness";

    protected $dataColumn = "bin";
    protected $dataSocrataKey = "bin";

    protected $primaryKey = 'cof_id';

    protected $table = 'fdny_cert_of_fitness';

    protected $updateFrequency = 'daily';
    protected $maps = [
        'bin__' => 'bin',
    ];

    protected $appends =['bin'];

    protected $notifiables = [
        "expires_on",
    ];

    protected $selectables = [
        "cof_id",
        "cof_num",
        "cof_type",
        "holder_name",
        "expires_on",
        "prem_addr",
        "bin",
        "communitydistrict",
        "citycouncildistrict",
        "bbl",
        "cent_latitude",
        "cent_longitude",
        "zipcode",
        "borough",
        "number",
        "street",
        "census_tract",
        "nta",
    ];


    protected $fillable = ["cof_id",
        "cof_num",
        "cof_type",
        "holder_name",
        "expires_on",
        "prem_addr",
        "bin",
        "communitydistrict",
        "citycouncildistrict",
        "bbl",
        "cent_latitude",
        "cent_longitude",
        "zipcode",
        "borough",
        "number",
        "street",
        "census_tract",
        "nta",];


    protected $casts = [
        'bin__' => 'string',
    ];

    public function expireDate()
    {
        return Helper::carbonParseYmd($this->expires_on);
    }

    public function scopeSummary($query)
    {
        return $query->where('expires_on', '>', '2018-01-01T00:00:00.000');
    }




//    protected function getWhereString()
//    {
//        return parent::getWhereString() . " and expires_on > '2018-01-01T00:00:00.000'"; // TODO: Change the autogenerated stub
//    }

}
