<?php

namespace App\Models;


use App\Helpers\Helper;

class LandmarkComplaints extends ODataModel
{
    public $subject = "New LANDMARK Complaint Filed";
    public $updateSubject = "New LANDMARK Complaint Status Update";
    public $reminderSubject = "LANDMARK Complaint Status Reminder";
    public $mailview = 'mails.alerts.landmarkComplaints';
    protected $datasetId = "ck4n-5h6x";
    protected $datasetName = "Landmarks Complaints";

    protected $dataColumn = "bin";
    protected $dataSocrataKey = "bin";

    protected $primaryKey = 'complaint';
    protected $updateFrequency = 'monthly';

    protected $table = 'landmark_complaints';

    protected $notifiables = [
        "date",
        "action_taken",
        "status",
    ];

    protected $selectables = [
        "complaint",
        "date",
        "action_taken",
        "status",
        "work_reported",
        "bin",
    ];

    protected $fillable = [
        "latitude",
        "address",
        "district",
        "date",
        "complaint",
        "borough",
        "action_taken",
        "census_tract",
        "additional_comments",
        "nta",
        "status",
        "work_reported",
        "street_name",
        "postcode",
        "community_council",
        "longitude",
        "community_board",
        "bin",
        "bbl"];


    public function date()
    {
        return Helper::carbonParseYmd($this->date);
    }

    public function scopeSummary($query)
    {
        return $query;
        // return $query->where('date', '>', '2018-01-01T00:00:00.000');
    }

//    protected function getWhereString()
//    {
//        return parent::getWhereString() . " and date > '2018-01-01T00:00:00.000'"; // TODO: Change the autogenerated stub
//    }

}
